In [106]:
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import load_model
import numpy as np
from colorthief import ColorThief

In [107]:
label_list = np.empty(0)

In [108]:
scene_model = load_model('scene-vgg19.h5')
rain_model = load_model('rain_vgg19.h5')
water_model = load_model('water_vgg19_kaggle.h5')
day_night_model = load_model('day_night_lenet.hd5')

In [109]:
def predict_class(model_name, photo ,classes):
    global label_list
    arr = np.zeros((classes))
    output  = model_name.predict(photo)
    print(output)
    arr[np.argmax(output)] = 1
    if(model_name == day_night_model):
        arr = arr[::-1]
    label_list = np.append(label_list, arr)

def predict_color(image_name):
    global label_list
    color_thief = ColorThief(image_name)
    dominant_color = color_thief.get_color(quality=1)
    temp_list = list(dominant_color)
    arr = np.zeros((3))
    arr[np.argmax(temp_list)] = 1
    arr = arr[::-1]
    label_list = np.append(label_list, arr)

In [110]:
def predict_rain(model_name, photo):
    global label_list
    arr = np.zeros((2))
    output = model_name.predict(photo)
    print(output)
    if(np.argmax(output) == 2):
        arr[1] = 1
    else:
        arr[0] = 1
    label_list = np.append(label_list, arr)


In [111]:
def predict_water(model_name, photo):
    global label_list
    arr = np.zeros((2))
    output = model_name.predict(photo)
    if(int(output + 0.5) == 1):
        arr[1] = 1
    else:
        arr[0] = 1
    label_list = np.append(label_list, arr)

In [112]:
img150 = image.load_img("Test Images/12.jpg",target_size=(150, 150))
img150 = np.asarray(img150)
img150 = np.expand_dims(img150, axis=0)
img28 = image.load_img("Test Images/12.jpg",target_size=(28, 28))
img28 = np.asarray(img28)
img28 = np.expand_dims(img28, axis=0)
img128 = image.load_img("Test Images/12.jpg",target_size=(128, 128))
img128 = np.asarray(img128)
img128 = np.expand_dims(img128, axis=0)

In [113]:
predict_class(day_night_model,img28, 2)

[[0. 1.]]


In [114]:
predict_color('Test Images/12.jpg')

In [115]:
predict_rain(rain_model, img150)

[[0. 0. 0. 1. 0.]]


In [116]:
predict_class(scene_model, img128, 5)

[[0.0000000e+00 1.0301472e-14 0.0000000e+00 0.0000000e+00 1.0000000e+00]]


In [117]:
predict_water(water_model, img150)

In [118]:
print(label_list)

[1. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0.]


In [119]:
classes = ['blues', 'country music', 'edm', 'hip hop', 'metal']

In [120]:

import pickle
loaded_model = pickle.load(open('label_model.sav', 'rb'))
label_input = label_list.reshape(1, -1)
result = loaded_model.predict(label_input)
print(classes[result[0]])

hip hop
